rss: rss.xml
name: Matthias Endler
description: Personal Blog
source: ./
dest: build
posts: blog
drafts: _drafts
ignore:
  - .git/*
  - build/*
  - img/raw/*
  - README.md
  - Makefile
  - todo.txt
  - LICENSE.txt
link: https://matthias-endler.de
syntax_highlight:
  theme: base16-ocean.light
